### ISSUE TITLE
PHP Stan zum überprüfen

### ISSUE THREAD

**Issue by Rindula** [Rindula/hirsch#387]
Config:

```yaml
- uses: actions/checkout@v2
- uses: php-actions/composer@v5

- name: PHPStan Static Analysis
  uses: php-actions/phpstan@v3
  with:
    path: src/
```
